'use client';

import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { PLC_BRANDS } from '@/lib/constants';
import { calculateCodeStats, copyToClipboard, formatTimestamp } from '@/lib/utils';
import { exportProjectPdf } from '@/lib/pdf-export';
import { generateWiring } from '@/lib/gemini-client';
import { PLCSyntaxHighlighter } from '../ui/syntax-highlighter';
import { CodeStatsBar } from '../ui/code-stats-bar';
import { WiringDiagram } from './wiring-diagram';
import type { GenerationResult, PLCBrandKey, WiringData } from '@/types';

interface CodePreviewProps {
  result: GenerationResult;
  onRefine?: (instruction: string) => Promise<unknown>;
  refining?: boolean;
}

export function CodePreview({ result, onRefine, refining = false }: CodePreviewProps) {
  const [copied, setCopied] = useState(false);
  const [exporting, setExporting] = useState(false);
  const [activeFile, setActiveFile] = useState<'main' | 'wiring' | 'stats' | 'info'>('main');
  const [instruction, setInstruction] = useState('');

  // Diagrama de conexión (se genera bajo demanda).
  const [wiring, setWiring] = useState<WiringData | null>(null);
  const [wiringLoading, setWiringLoading] = useState(false);
  const [wiringError, setWiringError] = useState('');

  const brand = PLC_BRANDS[result.plcBrand as PLCBrandKey];
  const stats = result.codeStats || calculateCodeStats(result.code);
  const ext = brand?.ext || '.txt';

  // Al cambiar de resultado se descarta el diagrama anterior.
  useEffect(() => {
    setWiring(null);
    setWiringError('');
    setActiveFile('main');
  }, [result.id]);

  const handleRefine = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!onRefine || !instruction.trim() || refining) return;
    try {
      const r = await onRefine(instruction.trim());
      if (r) setInstruction('');
    } catch {
      /* el error se muestra en el contenedor superior */
    }
  };

  const handleGenerateWiring = async () => {
    setWiringLoading(true);
    setWiringError('');
    try {
      const data = await generateWiring({
        description: result.description,
        plcBrand: result.plcBrand,
        language: result.language,
        code: result.code,
      });
      setWiring(data);
    } catch (err) {
      setWiringError(err instanceof Error ? err.message : 'No se pudo generar el diagrama.');
    } finally {
      setWiringLoading(false);
    }
  };

  // ... las funciones de descarga (exportWiringCsv, downloadAsFile, downloadAsZip) se mantienen igual en lógica
  const exportWiringCsv = () => { /* ... igual ... */ 
    if (!wiring) return;
    const cell = (v: string) => `"${String(v ?? '').replace(/"/g, '""')}"`;
    const lines: string[] = [];
    lines.push(['Tipo', 'Terminal', 'Tag', 'Dispositivo', 'Cable'].map(cell).join(','));
    for (const c of wiring.connections) {
      lines.push([c.type, c.terminal, c.tag, c.device, c.wire || ''].map(cell).join(','));
    }
    const blob = new Blob(['﻿' + lines.join('\n')], { type: 'text/csv;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Tablero_${result.plcBrand.replace(/[\s-]+/g, '_')}.csv`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleCopy = async () => {
    const ok = await copyToClipboard(result.code);
    if (ok) {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const downloadAsFile = () => {
    const fileName = `main_program${ext}`;
    const blob = new Blob([result.code], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = fileName;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const downloadAsZip = async () => {
    setExporting(true);
    try {
      const JSZip = (await import('jszip')).default;
      const zip = new JSZip();
      zip.file(`src/main_program${ext}`, result.code);
      zip.file('README.md', '# Generated by LogicPLC.ai');
      const blob = await zip.generateAsync({ type: 'blob' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `LogicPLC_Project_${Date.now()}.zip`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch (error) {
      console.error('Error al crear ZIP:', error);
    } finally {
      setExporting(false);
    }
  };

  // Archivos simulados en el árbol
  const fileTree = [
    { id: 'main', label: `main_program${ext}`, folder: 'src', icon: 'M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4' },
    { id: 'wiring', label: 'io_mapping.json', folder: 'config', icon: 'M9 3v2.25M15 3v2.25M9 18.75V21M15 18.75V21M6.75 6.75h10.5v10.5H6.75zM9.75 9.75h4.5v4.5h-4.5z' },
    { id: 'stats', label: 'analysis_stats.log', folder: 'build', icon: 'M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z' },
    { id: 'info', label: 'README.md', folder: 'docs', icon: 'M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z' },
  ] as const;

  return (
    <div className="flex flex-col h-[700px] w-full rounded-[24px] border border-slate-200/60 bg-white shadow-[0_8px_30px_rgb(0,0,0,0.06)] overflow-hidden font-sans">
      
      {/* ─── IDE Top Bar ─── */}
      <div className="flex items-center justify-between px-4 h-12 bg-slate-50 border-b border-slate-200/60 flex-shrink-0">
        <div className="flex items-center gap-4">
          <div className="flex items-center gap-1.5">
            <div className="w-3 h-3 rounded-full bg-[#ff5f56] border border-[#e0443e]" />
            <div className="w-3 h-3 rounded-full bg-[#ffbd2e] border border-[#dea123]" />
            <div className="w-3 h-3 rounded-full bg-[#27c93f] border border-[#1aab29]" />
          </div>
          <span className="text-[12px] font-medium text-slate-400 font-mono hidden sm:block">
            LogicPLC.ai / projects / workspace_{result.id.substring(0, 4)}
          </span>
        </div>
        
        <div className="flex items-center gap-2">
          {result.warning && (
            <span className="px-2 py-0.5 bg-amber-50 border border-amber-200 rounded text-[10px] text-amber-700 font-medium">
              Offline Mode
            </span>
          )}
          <div className="flex gap-1.5">
            <button onClick={downloadAsFile} className="w-8 h-8 flex items-center justify-center rounded border border-slate-200 bg-white hover:bg-slate-100 text-slate-500 transition-colors" title="Descargar Archivo">
              <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" /></svg>
            </button>
            <button onClick={downloadAsZip} className="w-8 h-8 flex items-center justify-center rounded bg-blue-600 hover:bg-blue-700 text-white transition-colors" title="Descargar Proyecto ZIP">
              <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M20.25 7.5l-.625 10.632a2.25 2.25 0 01-2.247 2.118H6.622a2.25 2.25 0 01-2.247-2.118L3.75 7.5M10 11.25h4M3.375 7.5h17.25c.621 0 1.125-.504 1.125-1.125v-1.5c0-.621-.504-1.125-1.125-1.125H3.375c-.621 0-1.125.504-1.125 1.125v1.5c0 .621.504 1.125 1.125 1.125z" /></svg>
            </button>
          </div>
        </div>
      </div>

      {/* ─── IDE Body ─── */}
      <div className="flex flex-col md:flex-row flex-1 overflow-hidden">
        
        {/* Mobile File Explorer */}
        <div className="md:hidden flex overflow-x-auto bg-slate-50/50 border-b border-slate-200/60 p-2 gap-2 flex-shrink-0 no-scrollbar">
          {fileTree.map((f) => (
            <button
              key={f.id}
              onClick={() => setActiveFile(f.id as any)}
              className={`flex items-center gap-2 px-3 py-1.5 rounded-md text-[12px] whitespace-nowrap transition-colors ${
                activeFile === f.id
                  ? 'bg-blue-100/50 text-blue-700 font-medium'
                  : 'text-slate-600 hover:bg-slate-200/50'
              }`}
            >
              <svg className={`w-3.5 h-3.5 ${activeFile === f.id ? 'text-blue-500' : 'text-slate-400'}`} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d={f.icon} />
              </svg>
              <span>{f.label}</span>
            </button>
          ))}
        </div>

        {/* Desktop Sidebar: File Explorer */}
        <div className="hidden md:flex w-56 bg-slate-50/50 border-r border-slate-200/60 flex-col flex-shrink-0">
          <div className="px-4 py-3 text-[10px] font-bold text-slate-400 tracking-widest uppercase">
            Explorador
          </div>
          <div className="flex flex-col gap-0.5 px-2">
            {fileTree.map((f) => (
              <button
                key={f.id}
                onClick={() => setActiveFile(f.id as any)}
                className={`flex items-center gap-2.5 px-3 py-1.5 rounded-md text-[12.5px] text-left transition-colors ${
                  activeFile === f.id
                    ? 'bg-blue-100/50 text-blue-700 font-medium'
                    : 'text-slate-600 hover:bg-slate-200/50'
                }`}
              >
                <svg className={`w-3.5 h-3.5 ${activeFile === f.id ? 'text-blue-500' : 'text-slate-400'}`} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                  <path strokeLinecap="round" strokeLinejoin="round" d={f.icon} />
                </svg>
                <span className="truncate">{f.label}</span>
              </button>
            ))}
          </div>
        </div>

        {/* Main Editor Area */}
        <div className="flex flex-col flex-1 bg-white overflow-hidden relative">
          
          {/* Editor Tabs */}
          <div className="flex items-end h-10 border-b border-slate-200/60 bg-slate-50/30 px-2 gap-1 flex-shrink-0">
            <div className="flex items-center gap-2 px-4 py-2 bg-white border-t border-l border-r border-slate-200/60 rounded-t-lg shadow-[0_-2px_5px_rgba(0,0,0,0.01)] relative top-[1px]">
              <svg className="w-3.5 h-3.5 text-slate-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d={fileTree.find(f => f.id === activeFile)?.icon} />
              </svg>
              <span className="text-[12px] font-mono text-slate-700">{fileTree.find(f => f.id === activeFile)?.label}</span>
              <button className="ml-2 hover:bg-slate-100 rounded-full p-0.5 text-slate-400 hover:text-slate-700">
                <svg className="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" /></svg>
              </button>
            </div>
          </div>

          {/* Active File Content */}
          <div className="flex-1 overflow-auto bg-[#0d1117] relative">
            <AnimatePresence mode="wait">
              
              {activeFile === 'main' && (
                <motion.div key="main" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="absolute inset-0">
                  <div className="absolute top-4 right-6 z-10">
                    <button
                      onClick={handleCopy}
                      className="text-[11px] font-mono bg-white/10 hover:bg-white/20 text-slate-300 hover:text-white transition-colors flex items-center gap-1.5 px-3 py-1.5 rounded"
                    >
                      {copied ? 'Copiado ✓' : 'Copiar'}
                    </button>
                  </div>
                  <PLCSyntaxHighlighter code={result.code} language={result.language} />
                </motion.div>
              )}

              {activeFile === 'wiring' && (
                <motion.div key="wiring" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="absolute inset-0 bg-white p-6 overflow-auto">
                  {!wiring ? (
                    <div className="flex flex-col items-center justify-center h-full text-center max-w-sm mx-auto">
                      <div className="w-16 h-16 rounded-2xl bg-blue-50 text-blue-500 flex items-center justify-center mb-6">
                         <svg className="w-8 h-8" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
                           <path strokeLinecap="round" strokeLinejoin="round" d="M9 3v2.25M15 3v2.25M9 18.75V21M15 18.75V21M6.75 6.75h10.5v10.5H6.75zM9.75 9.75h4.5v4.5h-4.5z" />
                         </svg>
                      </div>
                      <h4 className="text-slate-800 font-semibold mb-2">Generar Mapeo de I/O</h4>
                      <p className="text-slate-500 text-sm mb-6">Utiliza IA para analizar el código generado y extraer un esquema de conexiones eléctricas y BOM.</p>
                      <button
                        onClick={handleGenerateWiring}
                        disabled={wiringLoading}
                        className="px-6 py-2.5 bg-blue-600 hover:bg-blue-700 disabled:bg-slate-200 text-white text-sm font-medium rounded-lg w-full"
                      >
                        {wiringLoading ? 'Analizando...' : 'Generar io_mapping.json'}
                      </button>
                    </div>
                  ) : (
                    <div className="space-y-6">
                      <WiringDiagram data={wiring} />
                    </div>
                  )}
                </motion.div>
              )}

              {activeFile === 'stats' && (
                <motion.div key="stats" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="absolute inset-0 bg-slate-50 p-6 overflow-auto">
                  <CodeStatsBar stats={stats} />
                </motion.div>
              )}

              {activeFile === 'info' && (
                <motion.div key="info" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="absolute inset-0 bg-white p-8 overflow-auto prose prose-slate prose-sm max-w-none">
                  <h1>Proyecto LogicPLC</h1>
                  <p><strong>Fabricante:</strong> {brand?.manufacturer || result.plcBrand}</p>
                  <p><strong>Controlador:</strong> {brand?.model || ''} {result.plcModel ? ` (${result.plcModel})` : ''}</p>
                  <p><strong>Entorno:</strong> {brand?.software || 'N/A'}</p>
                  <p><strong>Lenguaje IEC:</strong> {result.language.toUpperCase()}</p>
                  <hr />
                  <h3>Especificación Original</h3>
                  <pre className="bg-slate-50 border border-slate-200 p-4 rounded-xl text-slate-700 whitespace-pre-wrap font-sans">
                    {result.description}
                  </pre>
                </motion.div>
              )}

            </AnimatePresence>
          </div>
        </div>
      </div>

      {/* ─── IDE Bottom Panel (Terminal / Refine) ─── */}
      <div className="h-44 border-t border-slate-200/60 bg-white flex flex-col flex-shrink-0">
        <div className="flex items-center px-4 h-8 bg-slate-50/50 border-b border-slate-200/60 gap-4">
          <span className="text-[11px] font-semibold text-slate-600 uppercase tracking-wider border-b-2 border-blue-500 h-full flex items-center">
            Terminal / Refinamiento
          </span>
          <span className="text-[11px] font-semibold text-slate-400 uppercase tracking-wider hover:text-slate-600 cursor-pointer h-full flex items-center">
            Problemas <span className="ml-1.5 w-4 h-4 rounded-full bg-slate-200 text-[9px] flex items-center justify-center text-slate-600">0</span>
          </span>
        </div>
        
        <div className="flex-1 p-3 overflow-hidden flex flex-col">
          {/* Simulated Compile Logs */}
          <div className="flex-1 font-mono text-[11px] text-slate-500 overflow-y-auto mb-2 opacity-80 pl-1">
            <p className="text-emerald-600">✓ Compilación inicial exitosa (0ms).</p>
            <p>» Analizando sintaxis {result.language.toUpperCase()}... OK</p>
            <p>» Vinculando bibliotecas para {brand?.software || 'el IDE'}... OK</p>
            <p className="text-blue-600">» Entorno LogicPLC AI listo. Escribe abajo para modificar el código.</p>
          </div>

          {/* Refine Input */}
          {onRefine && (
            <form onSubmit={handleRefine} className="flex gap-2">
              <div className="flex-1 flex items-center gap-2 bg-slate-50 border border-slate-200/60 rounded-md px-3">
                <span className="text-blue-500 font-mono text-sm">❯</span>
                <input
                  type="text"
                  value={instruction}
                  onChange={(e) => setInstruction(e.target.value)}
                  placeholder="Ej: Añade un temporizador de 5s antes de apagar la salida..."
                  disabled={refining}
                  className="flex-1 bg-transparent py-1.5 text-[13px] text-slate-800 placeholder-slate-400 focus:outline-none font-mono disabled:opacity-50"
                />
              </div>
              <button
                type="submit"
                disabled={refining || !instruction.trim()}
                className="px-4 bg-blue-600 hover:bg-blue-700 disabled:bg-slate-100 disabled:text-slate-400 text-white text-[12px] font-medium rounded-md transition-colors flex items-center gap-2"
              >
                {refining ? 'Procesando...' : 'Ejecutar'}
              </button>
            </form>
          )}
        </div>
      </div>

    </div>
  );
}
